import * as Icons from 'lucide-react';

export const availableIcons = [
  'Code', 'Palette', 'Globe', 'Newspaper', 'BookOpen', 'Bookmark', 'Heart',
  'Star', 'Zap', 'Music', 'Video', 'Camera', 'Image', 'FileText',
  'Folder', 'Briefcase', 'GraduationCap', 'Coffee', 'ShoppingBag',
  'DollarSign', 'TrendingUp', 'BarChart', 'PieChart', 'Activity',
  'Target', 'Flag', 'Map', 'Compass', 'Anchor', 'Rocket', 'Plane',
  'Car', 'Bike', 'Home', 'Building', 'Hospital', 'Banknote',
  'Shield', 'Lock', 'Key', 'Eye', 'Search', 'Filter', 'Settings',
  'Sliders', 'Tool', 'Wrench', 'Hammer', 'Cpu', 'Database', 'Server',
  'Cloud', 'Wifi', 'Bluetooth', 'Battery', 'Sun', 'Moon', 'CloudRain',
  'Thermometer', 'Flame', 'Droplets', 'Wind', 'Leaf', 'TreePine',
  'Flower', 'Feather', 'Scissors', 'PenTool', 'Pencil', 'Highlighter',
  'Type', 'AlignLeft', 'Table', 'Grid', 'Layout', 'Layers', 'Box',
  'Package', 'Gift', 'Award', 'Trophy', 'Medal', 'Crown', 'Gem',
  'Diamond', 'Sparkles', 'Magic', 'Wand', 'Ghost', 'Gamepad',
  'Dice', 'Puzzle', 'Brain', 'Lightbulb', 'MessageCircle', 'Mail',
  'Phone', 'Smartphone', 'Monitor', 'Laptop', 'Tablet', 'Watch',
  'Headphones', 'Speaker', 'Printer', 'Scan', 'Clipboard', 'Calendar',
  'Clock', 'Timer', 'Hourglass', 'Bell', 'Megaphone', 'Radio',
  'Tv', 'Film', 'Clapperboard', 'Theater', 'Mic', 'Podcast',
  'Rss', 'Share2', 'Link', 'ExternalLink', 'Paperclip', 'Tag',
  'Hash', 'AtSign', 'User', 'Users', 'UserPlus', 'UserCheck',
  'UserX', 'Smile', 'Frown', 'Laugh', 'Angry', 'Surprise',
  'ThumbsUp', 'ThumbsDown', 'Hand', 'Pointer', 'Mouse',
  'Keyboard', 'Command', 'Terminal', 'GitBranch', 'GitCommit',
  'GitMerge', 'GitPullRequest', 'Bug', 'AlertTriangle', 'Info',
  'HelpCircle', 'CheckCircle', 'XCircle', 'MinusCircle', 'PlusCircle',
  'CircleDot', 'Square', 'Triangle', 'Hexagon', 'Octagon',
  'StarOff', 'BookmarkX', 'Trash2', 'Archive', 'RotateCcw',
  'RefreshCw', 'Repeat', 'Shuffle', 'Move', 'Maximize', 'Minimize',
  'Expand', 'Shrink', 'Fullscreen', 'Columns', 'Rows', 'Split',
  'Merge', 'ChevronUp', 'ChevronDown', 'ChevronLeft', 'ChevronRight',
  'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'CornerUpLeft',
  'CornerUpRight', 'CornerDownLeft', 'CornerDownRight',
  'Undo', 'Redo', 'Copy', 'Cut', 'Paste', 'Save', 'Download',
  'Upload', 'CloudDownload', 'CloudUpload', 'Send', 'Inbox',
  'Outbox', 'FolderOpen', 'FolderPlus', 'FolderMinus', 'FolderX',
  'FilePlus', 'FileMinus', 'FileX', 'FileCheck', 'FileCode',
  'FileJson', 'FileSpreadsheet', 'FileImage', 'FileAudio',
  'FileVideo', 'FileArchive', 'FileSignature', 'FileUp',
  'Files', 'Scroll', 'Book', 'BookX', 'BookCheck', 'Library',
  'BookmarkPlus', 'BookmarkMinus', 'Sticker', 'StickerCheck',
  'Pin', 'PinOff', 'MapPin', 'Navigation', 'Locate', 'LocateFixed',
  'LocateOff', 'Crosshair', 'Focus', 'Aperture', 'ZoomIn',
  'ZoomOut', 'SearchX', 'List', 'ListChecks', 'ListOrdered',
  'ListTodo', 'CheckSquare', 'SquareCheck', 'SquareX',
  'SquareMinus', 'SquarePlus', 'Circle', 'CircleCheck',
  'CircleX', 'CircleMinus', 'CirclePlus', 'CircleAlert',
  'CircleHelp', 'CirclePause', 'CirclePlay', 'CircleStop',
  'CircleArrowUp', 'CircleArrowDown', 'CircleArrowLeft',
  'CircleArrowRight', 'CircleChevronUp', 'CircleChevronDown',
  'CircleChevronLeft', 'CircleChevronRight', 'CircleDashed',
  'CircleDotDashed', 'CircleEllipsis', 'CircleFadingPlus',
  'CircleGauge', 'CircleOff', 'CircleParking', 'CircleParkingOff',
  'CirclePercent', 'CirclePower', 'CircleSlash', 'CircleUser',
  'CircleUserRound', 'CircleDollarSign', 'CircleEuro',
  'CirclePoundSterling', 'CircleJapaneseYen', 'CircleIndianRupee',
  'CircleFadingArrowUp', 'CircleFadingPlus',
];

export function getIcon(name: string) {
  const iconMap = Icons as unknown as Record<string, React.ComponentType<{ className?: string; size?: number; style?: React.CSSProperties; color?: string }>>;
  return iconMap[name] || Icons.Circle;
}
